name: "File Count PR Creator"
description: "Counts files in the repository and creates a PR to update or add file_count with the total count."
author: "Devan"
branding:
  icon: "file-text"
  color: "blue"
inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
    default: ${{ github.token }}
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    WORKSPACE_PATH: "/github/workspace"
